/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */

export const media = {
  sm: {
    minWidth: 0,
  },
  md: {
    minWidth: 600,
  },
  lg: {
    minWidth: 840,
  },
  xl: {
    minWidth: 1200,
  },
};
