/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */

export const media = {
  md: {
    minWidth: 768,
  },
  lg: {
    minWidth: 1024,
  },
  xl: {
    minWidth: 1366,
  },
};
