/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */

export const media = {
  sm: {
    minWidth: 576,
  },
  md: {
    minWidth: 768,
  },
  lg: {
    minWidth: 992,
  },
  xl: {
    minWidth: 1200,
  },
};
