packages:
  - "packages/*"

catalog:
  typescript: 5.7.2
  prettier: ^3.5.0
  vite: ^6.0.11
  "@types/node": ^22.10.1
  "@svgr/core": 8.1.0
  "react-native-svg": 15.8.0

catalogs:
  tamagui:
    "@tamagui/animations-css": ^1.124.13
    "@tamagui/animations-moti": ^1.124.13
    "@tamagui/animations-react-native": ^1.124.13
    "@tamagui/build": ^1.124.13
    "@tamagui/stacks": ^1.124.13
    "@tamagui/config": ^1.124.13
    "@tamagui/core": ^1.124.13
    "@tamagui/web": ^1.124.13
    "@tamagui/vite-plugin": ^1.124.13
    "@tamagui/helpers-icon": ^1.124.13
  eslint9:
    eslint: 9.16.0
    "@eslint/js": 9.16.0
  vitest:
    vitest: ^3.0.4
    "@vitest/browser": ^3.0.4
    "@vitest/coverage-v8": ^3.0.4
  reactNative:
    "react-native": 0.78.0
    "@types/react-native": ^0.73.0
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  storybook:
    storybook: ^8.5.2
    "@storybook/addon-essentials": ^8.5.2
    "@storybook/addon-interactions": ^8.5.2
    "@storybook/addon-themes": ^8.5.2
    "@storybook/blocks": ^8.5.2
    "@storybook/experimental-addon-test": ^8.5.2
    "@storybook/manager-api": ^8.5.2
    "@storybook/react": ^8.5.2
    "@storybook/react-vite": ^8.5.2
    "@storybook/test": ^8.5.2
    "@storybook/theming": ^8.5.2
    "@storybook/vue3": ^8.5.2
    "@storybook/vue3-vite": ^8.5.2
