packages:
  - "packages/*"

catalog:
  typescript: 5.8.3
  globals: 16.1.0
  prettier: ^3.5.0
  vite: ^6.3.5
  "@types/node": ^22.10.1
  "@svgr/core": 8.1.0
  "react-native-svg": 15.11.2
  "react-native-reanimated": ~3.17.4
  "@react-native-community/blur": ^4.4.1
  "@floating-ui/react": ^0.27.16

catalogs:
  tamagui:
    "@tamagui/adapt": 1.132.23
    "@tamagui/animate": 1.132.23
    "@tamagui/animate-presence": 1.132.23
    "@tamagui/animations-css": 1.132.23
    "@tamagui/animations-moti": 1.132.23
    "@tamagui/animations-react-native": 1.132.23
    "@tamagui/build": 1.132.23
    "@tamagui/collapsible": 1.132.23
    "@tamagui/config": 1.132.23
    "@tamagui/core": 1.132.23
    "@tamagui/checkbox-headless": 1.132.23
    "@tamagui/compose-refs": 1.132.23
    "@tamagui/create-context": 1.132.23
    "@tamagui/dismissable": 1.132.23
    "@tamagui/floating": 1.132.23
    "@tamagui/focusable": 1.132.23
    "@tamagui/focus-scope": 1.132.23
    "@tamagui/next-plugin": 1.132.23
    "@tamagui/next-theme": 1.132.23
    "@tamagui/polyfill-dev": 1.132.23
    "@tamagui/radio-headless": 1.132.23
    "@tamagui/remove-scroll": 1.132.23
    "@tamagui/roving-focus": 1.132.23
    "@tamagui/switch-headless": 1.132.23
    "@tamagui/web": 1.132.23
    "@tamagui/vite-plugin": 1.132.23
    "@tamagui/helpers-icon": 1.132.23
    "@tamagui/popper": 1.132.23
    "@tamagui/portal": 1.132.23
    "@tamagui/scroll-view": 1.132.23
    "@tamagui/image": 1.132.23
    "@tamagui/use-controllable-state": 1.132.23
    "@tamagui/use-direction": 1.132.23
    "@tamagui/z-index-stack": 1.132.23
  eslint9:
    eslint: 9.26.0
    "@eslint/js": 9.26.0
  typescript-eslint:
    "typescript-eslint": 8.32.1
    "@typescript-eslint/eslint-plugin": 8.32.1
    "@typescript-eslint/parser": 8.32.1
  vitest:
    vitest: ^3.1.3
    "@vitest/browser": ^3.1.3
    "@vitest/coverage-v8": ^3.1.3
  reactNative:
    "react-native": 0.79.6
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  storybook:
    storybook: 8.6.12
    "@storybook/addon-essentials": 8.6.12
    "@storybook/addon-interactions": 8.6.12
    "@storybook/blocks": 8.6.12
    "@storybook/experimental-addon-test": 8.6.12
    "@storybook/manager-api": 8.6.12
    "@storybook/react": 8.6.12
    "@storybook/react-vite": 8.6.12
    "@storybook/test": 8.6.12
    "@storybook/theming": 8.6.12
    "@storybook/vue3": 8.6.12
    "@storybook/vue3-vite": 8.6.12
