packages:
  - "packages/*"

catalog:
  typescript: 5.8.2
  prettier: ^3.5.0
  vite: ^6.0.11
  "@types/node": ^22.10.1
  "@svgr/core": 8.1.0
  "react-native-svg": 15.8.0

catalogs:
  tamagui:
    "@tamagui/adapt": 1.126.7
    "@tamagui/animations-css": 1.126.7
    "@tamagui/animations-moti": 1.126.7
    "@tamagui/animations-react-native": 1.126.7
    "@tamagui/build": 1.126.7
    "@tamagui/config": 1.126.7
    "@tamagui/core": 1.126.7
    "@tamagui/checkbox-headless": 1.126.7
    "@tamagui/compose-refs": 1.126.7
    "@tamagui/create-context": 1.126.7
    "@tamagui/focusable": 1.126.7
    "@tamagui/radio-headless": 1.126.7
    "@tamagui/roving-focus": 1.126.7
    "@tamagui/web": 1.126.7
    "@tamagui/vite-plugin": 1.126.7
    "@tamagui/helpers-icon": 1.126.7
    "@tamagui/popover": 1.126.7
    "@tamagui/portal": 1.126.7
    "@tamagui/scroll-view": 1.126.7
    "@tamagui/image": 1.126.7
    "@tamagui/sheet": 1.126.7
    "@tamagui/dialog": 1.126.7
    "@tamagui/use-controllable-state": 1.126.7
    "@tamagui/use-direction": 1.126.7
    "@tamagui/animate-presence": 1.126.7
  eslint9:
    eslint: 9.16.0
    "@eslint/js": 9.16.0
  vitest:
    vitest: ^3.0.4
    "@vitest/browser": ^3.0.4
    "@vitest/coverage-v8": ^3.0.4
  reactNative:
    "react-native": 0.79.2
    "@types/react-native": ^0.73.0
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  storybook:
    storybook: 8.6.12
    "@storybook/addon-essentials": 8.6.12
    "@storybook/addon-interactions": 8.6.12
    "@storybook/blocks": 8.6.12
    "@storybook/experimental-addon-test": 8.6.12
    "@storybook/manager-api": 8.6.12
    "@storybook/react": 8.6.12
    "@storybook/react-vite": 8.6.12
    "@storybook/test": 8.6.12
    "@storybook/theming": 8.6.12
    "@storybook/vue3": 8.6.12
    "@storybook/vue3-vite": 8.6.12
