packages:
  - "packages/*"

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.1
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
  storybook:
    storybook: ^8.5.2
    "@storybook/addon-essentials": ^8.5.2
    "@storybook/addon-interactions": ^8.5.2
    "@storybook/addon-themes": ^8.5.2
    "@storybook/blocks": ^8.5.2
    "@storybook/experimental-addon-test": ^8.5.2
    "@storybook/manager-api": ^8.5.2
    "@storybook/react": ^8.5.2
    "@storybook/react-vite": ^8.5.2
    "@storybook/test": ^8.5.2
    "@storybook/theming": ^8.5.2
    "@storybook/vue3": ^8.5.2
    "@storybook/vue3-vite": ^8.5.2
