/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const accordion: {
    $500: {
        header: {
            gap: string;
        };
    };
};
export declare const badge: {
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            gap: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const board: {
    list: {
        large: {
            frame: {
                paddingLeft: string;
                paddingRight: string;
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
        medium: {
            frame: {
                paddingLeft: string;
                paddingRight: string;
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
    };
    cell: {
        large: {
            frame: {
                paddingLeft: string;
                paddingRight: string;
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
        medium: {
            frame: {
                paddingLeft: string;
                paddingRight: string;
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
        small: {
            frame: {
                paddingLeft: string;
                paddingRight: string;
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
    };
    accordion: {
        medium: {
            frame: {
                paddingLeft: string;
                paddingRight: string;
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
    };
};
export declare const breadcrumbs: {
    $500: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
};
export declare const button: {
    $200: {
        frame: {
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $300: {
        frame: {
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $400: {
        frame: {
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $500: {
        frame: {
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $600: {
        frame: {
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $700: {
        frame: {
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const cell: {
    size: {
        large: {
            frame: {
                gap: string;
                paddingVertical: string;
            };
            content: {
                minHeight: string;
                paddingVertical: string;
            };
            slot: {
                minHeight: string;
            };
        };
        medium: {
            frame: {
                gap: string;
                paddingVertical: string;
            };
            content: {
                minHeight: string;
                paddingVertical: string;
            };
            slot: {
                minHeight: string;
            };
        };
    };
    addon: {
        gap: string;
    };
};
export declare const chips: {
    $200: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
    $300: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
    $400: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
    $500: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
    $600: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
    $700: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
};
export declare const control: {
    $100: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $200: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $300: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $400: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $500: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $600: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $700: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $800: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $900: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
};
export declare const dropdown: {
    $400: {
        frame: {
            marginTop: string;
            padding: string;
            borderRadius: string;
        };
        content: {
            paddingHorizontal: string;
        };
    };
    $500: {
        frame: {
            marginTop: string;
            padding: string;
            borderRadius: string;
        };
        content: {
            paddingHorizontal: string;
        };
    };
    $600: {
        frame: {
            marginTop: string;
            padding: string;
            borderRadius: string;
        };
        content: {
            paddingHorizontal: string;
        };
    };
};
export declare const field: {
    $400: {
        frame: {
            gap: string;
        };
        label: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
        inputs: {
            gap: string;
        };
        hint: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
    };
    $500: {
        frame: {
            gap: string;
        };
        label: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
        inputs: {
            gap: string;
        };
        hint: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
    };
    $600: {
        frame: {
            gap: string;
        };
        label: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
        inputs: {
            gap: string;
        };
        hint: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const flexButton: {
    $300: {
        frame: {
            gap: string;
        };
        slot: {
            paddingLeft: string;
        };
    };
    $400: {
        frame: {
            gap: string;
        };
        slot: {
            paddingLeft: string;
        };
    };
    $500: {
        frame: {
            gap: string;
        };
        slot: {
            paddingLeft: string;
        };
    };
    $600: {
        frame: {
            gap: string;
        };
        slot: {
            paddingLeft: string;
        };
    };
};
export declare const input: {
    $400: {
        frame: {
            borderWidth: string;
            paddingVertical: string;
            paddingHorizontal: string;
        };
        label: {
            typography: string;
        };
    };
    $500: {
        frame: {
            borderWidth: string;
            paddingVertical: string;
            paddingHorizontal: string;
        };
        label: {
            typography: string;
        };
    };
    $600: {
        frame: {
            borderWidth: string;
            paddingVertical: string;
            paddingHorizontal: string;
        };
        label: {
            typography: string;
        };
    };
};
export declare const list: {
    $500: {
        frame: {
            gap: string;
        };
        title: {
            gap: string;
            typography: string;
        };
        subtitle: {
            gap: string;
            typography: string;
        };
    };
    $600: {
        frame: {
            gap: string;
        };
        title: {
            gap: string;
            typography: string;
        };
        subtitle: {
            gap: string;
            typography: string;
        };
    };
};
export declare const loader: {
    $500: {
        borderWidth: string;
    };
};
export declare const modal: {
    marginTop: string;
    marginBottom: string;
    borderRadius: string;
    header: {
        paddingVertical: string;
        gap: string;
    };
    content: {
        paddingTop: string;
        paddingBottom: string;
    };
    footer: {
        paddingTop: string;
        paddingBottom: string;
    };
};
export declare const navBar: {
    minHeight: string;
    addonLeft: {
        paddingLeft: string;
        paddingRight: string;
        gap: string;
    };
    addonRight: {
        paddingLeft: string;
        paddingRight: string;
        gap: string;
    };
    center: {
        gap: string;
    };
};
export declare const pimple: {
    $200: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $300: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $400: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $700: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
};
export declare const progressBar: {
    $500: {
        frame: {
            height: string;
            borderRadius: string;
        };
    };
};
export declare const richIcon: {
    $100: {
        icon: {
            size: string;
        };
    };
    $200: {
        icon: {
            size: string;
        };
    };
    $300: {
        icon: {
            size: string;
        };
    };
    $400: {
        icon: {
            size: string;
        };
    };
    $500: {
        icon: {
            size: string;
        };
    };
    $600: {
        icon: {
            size: string;
        };
    };
    $700: {
        icon: {
            size: string;
        };
    };
    $800: {
        icon: {
            size: string;
        };
    };
    $900: {
        icon: {
            size: string;
        };
    };
};
export declare const segmentedControl: {
    $300: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
    $400: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
    $500: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
    $600: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
};
export declare const selectionControl: {
    $400: {
        frame: {
            size: string;
            borderRadius: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
    $500: {
        frame: {
            size: string;
            borderRadius: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
    $600: {
        frame: {
            size: string;
            borderRadius: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
};
export declare const semanticText: {
    headerXl: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerL: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerM: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerS: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerXs: {
        paddingTop: string;
        paddingBottom: string;
    };
    paragraphL: {
        paddingTop: string;
        paddingBottom: string;
    };
    paragraphM: {
        paddingTop: string;
        paddingBottom: string;
    };
    paragraphS: {
        paddingTop: string;
        paddingBottom: string;
    };
};
export declare const components: {
    accordion: {
        $500: {
            header: {
                gap: string;
            };
        };
    };
    badge: {
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                gap: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    board: {
        list: {
            large: {
                frame: {
                    paddingLeft: string;
                    paddingRight: string;
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
            medium: {
                frame: {
                    paddingLeft: string;
                    paddingRight: string;
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
        };
        cell: {
            large: {
                frame: {
                    paddingLeft: string;
                    paddingRight: string;
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
            medium: {
                frame: {
                    paddingLeft: string;
                    paddingRight: string;
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
            small: {
                frame: {
                    paddingLeft: string;
                    paddingRight: string;
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
        };
        accordion: {
            medium: {
                frame: {
                    paddingLeft: string;
                    paddingRight: string;
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
        };
    };
    breadcrumbs: {
        $500: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
    };
    button: {
        $200: {
            frame: {
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $300: {
            frame: {
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $400: {
            frame: {
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $500: {
            frame: {
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $700: {
            frame: {
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    cell: {
        size: {
            large: {
                frame: {
                    gap: string;
                    paddingVertical: string;
                };
                content: {
                    minHeight: string;
                    paddingVertical: string;
                };
                slot: {
                    minHeight: string;
                };
            };
            medium: {
                frame: {
                    gap: string;
                    paddingVertical: string;
                };
                content: {
                    minHeight: string;
                    paddingVertical: string;
                };
                slot: {
                    minHeight: string;
                };
            };
        };
        addon: {
            gap: string;
        };
    };
    chips: {
        $200: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
        $300: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
        $400: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
        $500: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
        $700: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
    };
    control: {
        $100: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $200: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $300: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $400: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $500: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $600: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $700: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $800: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $900: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
    };
    dropdown: {
        $400: {
            frame: {
                marginTop: string;
                padding: string;
                borderRadius: string;
            };
            content: {
                paddingHorizontal: string;
            };
        };
        $500: {
            frame: {
                marginTop: string;
                padding: string;
                borderRadius: string;
            };
            content: {
                paddingHorizontal: string;
            };
        };
        $600: {
            frame: {
                marginTop: string;
                padding: string;
                borderRadius: string;
            };
            content: {
                paddingHorizontal: string;
            };
        };
    };
    field: {
        $400: {
            frame: {
                gap: string;
            };
            label: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
            inputs: {
                gap: string;
            };
            hint: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
        };
        $500: {
            frame: {
                gap: string;
            };
            label: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
            inputs: {
                gap: string;
            };
            hint: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
            label: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
            inputs: {
                gap: string;
            };
            hint: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    flexButton: {
        $300: {
            frame: {
                gap: string;
            };
            slot: {
                paddingLeft: string;
            };
        };
        $400: {
            frame: {
                gap: string;
            };
            slot: {
                paddingLeft: string;
            };
        };
        $500: {
            frame: {
                gap: string;
            };
            slot: {
                paddingLeft: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
            slot: {
                paddingLeft: string;
            };
        };
    };
    input: {
        $400: {
            frame: {
                borderWidth: string;
                paddingVertical: string;
                paddingHorizontal: string;
            };
            label: {
                typography: string;
            };
        };
        $500: {
            frame: {
                borderWidth: string;
                paddingVertical: string;
                paddingHorizontal: string;
            };
            label: {
                typography: string;
            };
        };
        $600: {
            frame: {
                borderWidth: string;
                paddingVertical: string;
                paddingHorizontal: string;
            };
            label: {
                typography: string;
            };
        };
    };
    list: {
        $500: {
            frame: {
                gap: string;
            };
            title: {
                gap: string;
                typography: string;
            };
            subtitle: {
                gap: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
            title: {
                gap: string;
                typography: string;
            };
            subtitle: {
                gap: string;
                typography: string;
            };
        };
    };
    loader: {
        $500: {
            borderWidth: string;
        };
    };
    modal: {
        marginTop: string;
        marginBottom: string;
        borderRadius: string;
        header: {
            paddingVertical: string;
            gap: string;
        };
        content: {
            paddingTop: string;
            paddingBottom: string;
        };
        footer: {
            paddingTop: string;
            paddingBottom: string;
        };
    };
    navBar: {
        minHeight: string;
        addonLeft: {
            paddingLeft: string;
            paddingRight: string;
            gap: string;
        };
        addonRight: {
            paddingLeft: string;
            paddingRight: string;
            gap: string;
        };
        center: {
            gap: string;
        };
    };
    pimple: {
        $200: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $300: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $400: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $700: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
    };
    progressBar: {
        $500: {
            frame: {
                height: string;
                borderRadius: string;
            };
        };
    };
    richIcon: {
        $100: {
            icon: {
                size: string;
            };
        };
        $200: {
            icon: {
                size: string;
            };
        };
        $300: {
            icon: {
                size: string;
            };
        };
        $400: {
            icon: {
                size: string;
            };
        };
        $500: {
            icon: {
                size: string;
            };
        };
        $600: {
            icon: {
                size: string;
            };
        };
        $700: {
            icon: {
                size: string;
            };
        };
        $800: {
            icon: {
                size: string;
            };
        };
        $900: {
            icon: {
                size: string;
            };
        };
    };
    segmentedControl: {
        $300: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
        $400: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
        $500: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
        $600: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
    };
    selectionControl: {
        $400: {
            frame: {
                size: string;
                borderRadius: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
        $500: {
            frame: {
                size: string;
                borderRadius: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
        $600: {
            frame: {
                size: string;
                borderRadius: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
    };
    semanticText: {
        headerXl: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerL: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerM: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerS: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerXs: {
            paddingTop: string;
            paddingBottom: string;
        };
        paragraphL: {
            paddingTop: string;
            paddingBottom: string;
        };
        paragraphM: {
            paddingTop: string;
            paddingBottom: string;
        };
        paragraphS: {
            paddingTop: string;
            paddingBottom: string;
        };
    };
};
//# sourceMappingURL=components.d.ts.map