/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const accordion: {
    size: {
        medium: {
            header: {
                gap: string;
            };
        };
    };
    board: {
        medium: {
            frame: {
                paddingLeft: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
                paddingRight: string;
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
    };
};
export declare const badge: {
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            gap: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const breadcrumbs: {
    $500: {
        frame: {
            gap: string;
        };
        item: {
            typography: string;
        };
    };
};
export declare const button: {
    $200: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $300: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $400: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $700: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const cell: {
    size: {
        large: {
            frame: {
                gap: string;
                paddingVertical: string;
            };
            content: {
                minHeight: string;
                paddingVertical: string;
            };
            slot: {
                minHeight: string;
            };
        };
        medium: {
            frame: {
                gap: string;
                paddingVertical: string;
            };
            content: {
                minHeight: string;
                paddingVertical: string;
            };
            slot: {
                minHeight: string;
            };
        };
    };
    addon: {
        gap: string;
    };
    board: {
        large: {
            frame: {
                paddingHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
        medium: {
            frame: {
                paddingHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
        small: {
            frame: {
                paddingHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
    };
};
export declare const checkbox: {
    $400: {
        frame: {
            size: string;
            borderRadius: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
    $500: {
        frame: {
            size: string;
            borderRadius: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
    $600: {
        frame: {
            size: string;
            borderRadius: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
};
export declare const chip: {
    $200: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $300: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $400: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $700: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const chips: {
    $200: {
        frame: {
            gap: string;
        };
    };
    $300: {
        frame: {
            gap: string;
        };
    };
    $400: {
        frame: {
            gap: string;
        };
    };
    $500: {
        frame: {
            gap: string;
        };
    };
    $600: {
        frame: {
            gap: string;
        };
    };
    $700: {
        frame: {
            gap: string;
        };
    };
};
export declare const dropdown: {
    $400: {
        frame: {
            marginTop: string;
            padding: string;
            borderRadius: string;
        };
        content: {
            paddingHorizontal: string;
        };
    };
    $500: {
        frame: {
            marginTop: string;
            padding: string;
            borderRadius: string;
        };
        content: {
            paddingHorizontal: string;
        };
    };
    $600: {
        frame: {
            marginTop: string;
            padding: string;
            borderRadius: string;
        };
        content: {
            paddingHorizontal: string;
        };
    };
};
export declare const field: {
    $400: {
        frame: {
            gap: string;
        };
        label: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
        inputs: {
            gap: string;
        };
        hint: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
    };
    $500: {
        frame: {
            gap: string;
        };
        label: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
        inputs: {
            gap: string;
        };
        hint: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
    };
    $600: {
        frame: {
            gap: string;
        };
        label: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
        inputs: {
            gap: string;
        };
        hint: {
            gap: string;
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const flexButton: {
    $300: {
        frame: {
            gap: string;
            minHeight: string;
        };
        slot: {
            paddingLeft: string;
        };
        label: {
            typography: string;
        };
        icon: {
            size: string;
        };
    };
    $400: {
        frame: {
            gap: string;
            minHeight: string;
        };
        slot: {
            paddingLeft: string;
        };
        label: {
            typography: string;
        };
        icon: {
            size: string;
        };
    };
    $500: {
        frame: {
            gap: string;
            minHeight: string;
        };
        slot: {
            paddingLeft: string;
        };
        label: {
            typography: string;
        };
        icon: {
            size: string;
        };
    };
    $600: {
        frame: {
            gap: string;
            minHeight: string;
        };
        slot: {
            paddingLeft: string;
        };
        label: {
            typography: string;
        };
        icon: {
            size: string;
        };
    };
};
export declare const gallery: {
    $500: {
        gap: string;
    };
};
export declare const inlineInput: {
    $400: {
        typography: string;
    };
    $500: {
        typography: string;
    };
    $600: {
        typography: string;
    };
};
export declare const input: {
    $400: {
        frame: {
            minSize: string;
            borderRadius: string;
            gap: string;
            borderWidth: string;
            paddingVertical: string;
            paddingHorizontal: string;
        };
        label: {
            typography: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            gap: string;
            borderWidth: string;
            paddingVertical: string;
            paddingHorizontal: string;
        };
        label: {
            typography: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
            borderRadius: string;
            gap: string;
            borderWidth: string;
            paddingVertical: string;
            paddingHorizontal: string;
        };
        label: {
            typography: string;
        };
    };
};
export declare const list: {
    size: {
        $500: {
            frame: {
                gap: string;
            };
            title: {
                gap: string;
                typography: string;
            };
            subtitle: {
                gap: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
            title: {
                gap: string;
                typography: string;
            };
            subtitle: {
                gap: string;
                typography: string;
            };
        };
    };
    board: {
        $500: {
            frame: {
                paddingHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
        $600: {
            frame: {
                paddingHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
                paddingVertical: string;
                borderRadius: string;
            };
            content: {
                minHeight: string;
            };
        };
    };
};
export declare const loader: {
    $500: {
        borderWidth: string;
    };
};
export declare const modal: {
    $500: {
        frame: {
            marginVertical: {
                base: string;
                $md: string;
                $xl: string;
            };
            marginHorizontal: {
                base: string;
                $md: string;
                $lg: string;
                $xl: string;
            };
            borderRadius: {
                base: string;
                $lg: string;
            };
        };
        header: {
            paddingVertical: string;
        };
        content: {
            paddingTop: {
                base: string;
                $lg: string;
                $xl: string;
            };
            paddingBottom: {
                base: string;
                $lg: string;
                $xl: string;
            };
        };
        footer: {
            paddingBottom: {
                base: string;
                $md: string;
                $lg: string;
                $xl: string;
            };
        };
    };
};
export declare const navBar: {
    size: {
        $500: {
            frame: {
                minHeight: {
                    base: string;
                    $lg: string;
                    $xl: string;
                };
                paddingHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
            };
            content: {
                gap: string;
                paddingHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
            };
            addon: {
                gap: string;
            };
        };
    };
    center: {
        default: {
            gap: string;
            title: {
                typography: string;
            };
            subtitle: {
                typography: string;
            };
        };
        prominent: {
            gap: string;
            title: {
                typography: string;
            };
            subtitle: {
                typography: string;
            };
        };
    };
};
export declare const pimple: {
    $200: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $300: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $400: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
    $700: {
        frame: {
            minSize: string;
            borderRadius: string;
            paddingHorizontal: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
};
export declare const progressBar: {
    $500: {
        frame: {
            height: string;
            borderRadius: string;
        };
    };
};
export declare const radio: {
    $400: {
        frame: {
            size: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
    $500: {
        frame: {
            size: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
    $600: {
        frame: {
            size: string;
            borderWidth: string;
        };
        icon: {
            size: string;
        };
    };
};
export declare const richIcon: {
    $100: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $200: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $300: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $400: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $700: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $800: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
    $900: {
        frame: {
            minSize: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
            paddingHorizontal: string;
            paddingTop: string;
        };
    };
};
export declare const segment: {
    $400: {
        frame: {
            minSize: string;
            borderRadius: string;
            borderWidth: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
            borderRadius: string;
            borderWidth: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
            borderRadius: string;
            borderWidth: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
    $700: {
        frame: {
            minSize: string;
            borderRadius: string;
            borderWidth: string;
            paddingHorizontal: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
            typography: string;
        };
    };
};
export declare const segmentedControl: {
    $400: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
    $500: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
    $600: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
    $700: {
        frame: {
            paddingHorizontal: string;
            paddingVertical: string;
            borderRadius: string;
            borderWidth: string;
        };
    };
};
export declare const semanticText: {
    headerXl: {
        paddingTop: string;
        paddingBottom: {
            base: string;
            $lg: string;
        };
        typography: {
            base: string;
            $lg: string;
            $xl: string;
        };
    };
    headerL: {
        paddingTop: {
            base: string;
            $xl: string;
        };
        paddingBottom: string;
        typography: {
            base: string;
            $lg: string;
            $xl: string;
        };
    };
    headerM: {
        paddingTop: string;
        paddingBottom: string;
        typography: {
            base: string;
            $lg: string;
            $xl: string;
        };
    };
    headerS: {
        paddingTop: {
            base: string;
            $lg: string;
            $xl: string;
        };
        paddingBottom: {
            base: string;
            $lg: string;
        };
        typography: {
            base: string;
            $lg: string;
            $xl: string;
        };
    };
    headerXs: {
        paddingTop: {
            base: string;
            $lg: string;
            $xl: string;
        };
        paddingBottom: string;
        typography: {
            base: string;
            $lg: string;
            $xl: string;
        };
    };
    paragraphL: {
        paddingTop: string;
        paddingBottom: string;
        typography: {
            base: string;
            $lg: string;
        };
    };
    paragraphM: {
        paddingTop: {
            base: string;
            $lg: string;
        };
        paddingBottom: {
            base: string;
            $lg: string;
        };
        typography: {
            base: string;
            $lg: string;
        };
    };
    paragraphS: {
        paddingTop: string;
        paddingBottom: string;
        typography: {
            base: string;
            $lg: string;
        };
    };
};
export declare const separator: {
    $500: {
        borderWidth: string;
    };
};
export declare const slider: {
    $500: {
        frame: {
            height: string;
            borderRadius: string;
        };
        knob: {
            size: string;
            borderWidth: string;
        };
    };
};
export declare const switchComponent: {
    $600: {
        frame: {
            borderRadius: string;
            borderWidth: string;
            padding: string;
        };
        knob: {
            size: string;
            borderRadius: string;
        };
    };
};
export declare const tabs: {
    $300: {
        frame: {
            gap: string;
        };
    };
    $400: {
        frame: {
            gap: string;
        };
    };
    $500: {
        frame: {
            gap: string;
        };
    };
    $600: {
        frame: {
            gap: string;
        };
    };
    $700: {
        frame: {
            gap: string;
        };
    };
};
export declare const tabBar: {
    $500: {
        tab: {
            minHeight: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
    };
};
export declare const tab: {
    $300: {
        frame: {
            minSize: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
        slot: {
            paddingLeft: string;
        };
        line: {
            height: string;
            borderTopLeftRadius: string;
            borderTopRightRadius: string;
            borderBottomLeftRadius: string;
            borderBottomRightRadius: string;
        };
    };
    $400: {
        frame: {
            minSize: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
        slot: {
            paddingLeft: string;
        };
        line: {
            height: string;
            borderTopLeftRadius: string;
            borderTopRightRadius: string;
            borderBottomLeftRadius: string;
            borderBottomRightRadius: string;
        };
    };
    $500: {
        frame: {
            minSize: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
        slot: {
            paddingLeft: string;
        };
        line: {
            height: string;
            borderTopLeftRadius: string;
            borderTopRightRadius: string;
            borderBottomLeftRadius: string;
            borderBottomRightRadius: string;
        };
    };
    $600: {
        frame: {
            minSize: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
        slot: {
            paddingLeft: string;
        };
        line: {
            height: string;
            borderTopLeftRadius: string;
            borderTopRightRadius: string;
            borderBottomLeftRadius: string;
            borderBottomRightRadius: string;
        };
    };
    $700: {
        frame: {
            minSize: string;
            gap: string;
        };
        icon: {
            size: string;
        };
        label: {
            typography: string;
        };
        slot: {
            paddingLeft: string;
        };
        line: {
            height: string;
            borderTopLeftRadius: string;
            borderTopRightRadius: string;
            borderBottomLeftRadius: string;
            borderBottomRightRadius: string;
        };
    };
};
export declare const components: {
    accordion: {
        size: {
            medium: {
                header: {
                    gap: string;
                };
            };
        };
        board: {
            medium: {
                frame: {
                    paddingLeft: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                    paddingRight: string;
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
        };
    };
    badge: {
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                gap: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    breadcrumbs: {
        $500: {
            frame: {
                gap: string;
            };
            item: {
                typography: string;
            };
        };
    };
    button: {
        $200: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $300: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $400: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $700: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    cell: {
        size: {
            large: {
                frame: {
                    gap: string;
                    paddingVertical: string;
                };
                content: {
                    minHeight: string;
                    paddingVertical: string;
                };
                slot: {
                    minHeight: string;
                };
            };
            medium: {
                frame: {
                    gap: string;
                    paddingVertical: string;
                };
                content: {
                    minHeight: string;
                    paddingVertical: string;
                };
                slot: {
                    minHeight: string;
                };
            };
        };
        addon: {
            gap: string;
        };
        board: {
            large: {
                frame: {
                    paddingHorizontal: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
            medium: {
                frame: {
                    paddingHorizontal: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
            small: {
                frame: {
                    paddingHorizontal: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
        };
    };
    checkbox: {
        $400: {
            frame: {
                size: string;
                borderRadius: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
        $500: {
            frame: {
                size: string;
                borderRadius: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
        $600: {
            frame: {
                size: string;
                borderRadius: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
    };
    chip: {
        $200: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $300: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $400: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $700: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    chips: {
        $200: {
            frame: {
                gap: string;
            };
        };
        $300: {
            frame: {
                gap: string;
            };
        };
        $400: {
            frame: {
                gap: string;
            };
        };
        $500: {
            frame: {
                gap: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
        };
        $700: {
            frame: {
                gap: string;
            };
        };
    };
    dropdown: {
        $400: {
            frame: {
                marginTop: string;
                padding: string;
                borderRadius: string;
            };
            content: {
                paddingHorizontal: string;
            };
        };
        $500: {
            frame: {
                marginTop: string;
                padding: string;
                borderRadius: string;
            };
            content: {
                paddingHorizontal: string;
            };
        };
        $600: {
            frame: {
                marginTop: string;
                padding: string;
                borderRadius: string;
            };
            content: {
                paddingHorizontal: string;
            };
        };
    };
    field: {
        $400: {
            frame: {
                gap: string;
            };
            label: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
            inputs: {
                gap: string;
            };
            hint: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
        };
        $500: {
            frame: {
                gap: string;
            };
            label: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
            inputs: {
                gap: string;
            };
            hint: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
            label: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
            inputs: {
                gap: string;
            };
            hint: {
                gap: string;
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    flexButton: {
        $300: {
            frame: {
                gap: string;
                minHeight: string;
            };
            slot: {
                paddingLeft: string;
            };
            label: {
                typography: string;
            };
            icon: {
                size: string;
            };
        };
        $400: {
            frame: {
                gap: string;
                minHeight: string;
            };
            slot: {
                paddingLeft: string;
            };
            label: {
                typography: string;
            };
            icon: {
                size: string;
            };
        };
        $500: {
            frame: {
                gap: string;
                minHeight: string;
            };
            slot: {
                paddingLeft: string;
            };
            label: {
                typography: string;
            };
            icon: {
                size: string;
            };
        };
        $600: {
            frame: {
                gap: string;
                minHeight: string;
            };
            slot: {
                paddingLeft: string;
            };
            label: {
                typography: string;
            };
            icon: {
                size: string;
            };
        };
    };
    gallery: {
        $500: {
            gap: string;
        };
    };
    inlineInput: {
        $400: {
            typography: string;
        };
        $500: {
            typography: string;
        };
        $600: {
            typography: string;
        };
    };
    input: {
        $400: {
            frame: {
                minSize: string;
                borderRadius: string;
                gap: string;
                borderWidth: string;
                paddingVertical: string;
                paddingHorizontal: string;
            };
            label: {
                typography: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                gap: string;
                borderWidth: string;
                paddingVertical: string;
                paddingHorizontal: string;
            };
            label: {
                typography: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
                borderRadius: string;
                gap: string;
                borderWidth: string;
                paddingVertical: string;
                paddingHorizontal: string;
            };
            label: {
                typography: string;
            };
        };
    };
    list: {
        size: {
            $500: {
                frame: {
                    gap: string;
                };
                title: {
                    gap: string;
                    typography: string;
                };
                subtitle: {
                    gap: string;
                    typography: string;
                };
            };
            $600: {
                frame: {
                    gap: string;
                };
                title: {
                    gap: string;
                    typography: string;
                };
                subtitle: {
                    gap: string;
                    typography: string;
                };
            };
        };
        board: {
            $500: {
                frame: {
                    paddingHorizontal: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
            $600: {
                frame: {
                    paddingHorizontal: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                    paddingVertical: string;
                    borderRadius: string;
                };
                content: {
                    minHeight: string;
                };
            };
        };
    };
    loader: {
        $500: {
            borderWidth: string;
        };
    };
    modal: {
        $500: {
            frame: {
                marginVertical: {
                    base: string;
                    $md: string;
                    $xl: string;
                };
                marginHorizontal: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
                borderRadius: {
                    base: string;
                    $lg: string;
                };
            };
            header: {
                paddingVertical: string;
            };
            content: {
                paddingTop: {
                    base: string;
                    $lg: string;
                    $xl: string;
                };
                paddingBottom: {
                    base: string;
                    $lg: string;
                    $xl: string;
                };
            };
            footer: {
                paddingBottom: {
                    base: string;
                    $md: string;
                    $lg: string;
                    $xl: string;
                };
            };
        };
    };
    navBar: {
        size: {
            $500: {
                frame: {
                    minHeight: {
                        base: string;
                        $lg: string;
                        $xl: string;
                    };
                    paddingHorizontal: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                };
                content: {
                    gap: string;
                    paddingHorizontal: {
                        base: string;
                        $md: string;
                        $lg: string;
                        $xl: string;
                    };
                };
                addon: {
                    gap: string;
                };
            };
        };
        center: {
            default: {
                gap: string;
                title: {
                    typography: string;
                };
                subtitle: {
                    typography: string;
                };
            };
            prominent: {
                gap: string;
                title: {
                    typography: string;
                };
                subtitle: {
                    typography: string;
                };
            };
        };
    };
    pimple: {
        $200: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $300: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $400: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
        $700: {
            frame: {
                minSize: string;
                borderRadius: string;
                paddingHorizontal: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
    };
    progressBar: {
        $500: {
            frame: {
                height: string;
                borderRadius: string;
            };
        };
    };
    radio: {
        $400: {
            frame: {
                size: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
        $500: {
            frame: {
                size: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
        $600: {
            frame: {
                size: string;
                borderWidth: string;
            };
            icon: {
                size: string;
            };
        };
    };
    richIcon: {
        $100: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $200: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $300: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $400: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $700: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $800: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
        $900: {
            frame: {
                minSize: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
                paddingHorizontal: string;
                paddingTop: string;
            };
        };
    };
    segment: {
        $400: {
            frame: {
                minSize: string;
                borderRadius: string;
                borderWidth: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
                borderRadius: string;
                borderWidth: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
                borderRadius: string;
                borderWidth: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
        $700: {
            frame: {
                minSize: string;
                borderRadius: string;
                borderWidth: string;
                paddingHorizontal: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
                typography: string;
            };
        };
    };
    segmentedControl: {
        $400: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
        $500: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
        $600: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
        $700: {
            frame: {
                paddingHorizontal: string;
                paddingVertical: string;
                borderRadius: string;
                borderWidth: string;
            };
        };
    };
    semanticText: {
        headerXl: {
            paddingTop: string;
            paddingBottom: {
                base: string;
                $lg: string;
            };
            typography: {
                base: string;
                $lg: string;
                $xl: string;
            };
        };
        headerL: {
            paddingTop: {
                base: string;
                $xl: string;
            };
            paddingBottom: string;
            typography: {
                base: string;
                $lg: string;
                $xl: string;
            };
        };
        headerM: {
            paddingTop: string;
            paddingBottom: string;
            typography: {
                base: string;
                $lg: string;
                $xl: string;
            };
        };
        headerS: {
            paddingTop: {
                base: string;
                $lg: string;
                $xl: string;
            };
            paddingBottom: {
                base: string;
                $lg: string;
            };
            typography: {
                base: string;
                $lg: string;
                $xl: string;
            };
        };
        headerXs: {
            paddingTop: {
                base: string;
                $lg: string;
                $xl: string;
            };
            paddingBottom: string;
            typography: {
                base: string;
                $lg: string;
                $xl: string;
            };
        };
        paragraphL: {
            paddingTop: string;
            paddingBottom: string;
            typography: {
                base: string;
                $lg: string;
            };
        };
        paragraphM: {
            paddingTop: {
                base: string;
                $lg: string;
            };
            paddingBottom: {
                base: string;
                $lg: string;
            };
            typography: {
                base: string;
                $lg: string;
            };
        };
        paragraphS: {
            paddingTop: string;
            paddingBottom: string;
            typography: {
                base: string;
                $lg: string;
            };
        };
    };
    separator: {
        $500: {
            borderWidth: string;
        };
    };
    slider: {
        $500: {
            frame: {
                height: string;
                borderRadius: string;
            };
            knob: {
                size: string;
                borderWidth: string;
            };
        };
    };
    switchComponent: {
        $600: {
            frame: {
                borderRadius: string;
                borderWidth: string;
                padding: string;
            };
            knob: {
                size: string;
                borderRadius: string;
            };
        };
    };
    tabs: {
        $300: {
            frame: {
                gap: string;
            };
        };
        $400: {
            frame: {
                gap: string;
            };
        };
        $500: {
            frame: {
                gap: string;
            };
        };
        $600: {
            frame: {
                gap: string;
            };
        };
        $700: {
            frame: {
                gap: string;
            };
        };
    };
    tabBar: {
        $500: {
            tab: {
                minHeight: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
        };
    };
    tab: {
        $300: {
            frame: {
                minSize: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
            slot: {
                paddingLeft: string;
            };
            line: {
                height: string;
                borderTopLeftRadius: string;
                borderTopRightRadius: string;
                borderBottomLeftRadius: string;
                borderBottomRightRadius: string;
            };
        };
        $400: {
            frame: {
                minSize: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
            slot: {
                paddingLeft: string;
            };
            line: {
                height: string;
                borderTopLeftRadius: string;
                borderTopRightRadius: string;
                borderBottomLeftRadius: string;
                borderBottomRightRadius: string;
            };
        };
        $500: {
            frame: {
                minSize: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
            slot: {
                paddingLeft: string;
            };
            line: {
                height: string;
                borderTopLeftRadius: string;
                borderTopRightRadius: string;
                borderBottomLeftRadius: string;
                borderBottomRightRadius: string;
            };
        };
        $600: {
            frame: {
                minSize: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
            slot: {
                paddingLeft: string;
            };
            line: {
                height: string;
                borderTopLeftRadius: string;
                borderTopRightRadius: string;
                borderBottomLeftRadius: string;
                borderBottomRightRadius: string;
            };
        };
        $700: {
            frame: {
                minSize: string;
                gap: string;
            };
            icon: {
                size: string;
            };
            label: {
                typography: string;
            };
            slot: {
                paddingLeft: string;
            };
            line: {
                height: string;
                borderTopLeftRadius: string;
                borderTopRightRadius: string;
                borderBottomLeftRadius: string;
                borderBottomRightRadius: string;
            };
        };
    };
};
//# sourceMappingURL=components.d.ts.map