/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const button: {
    $200: {
        paddingHorizontal: string;
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
        };
    };
    $300: {
        paddingHorizontal: string;
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
        };
    };
    $400: {
        paddingHorizontal: string;
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
        };
    };
    $500: {
        paddingHorizontal: string;
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
        };
    };
    $600: {
        paddingHorizontal: string;
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
        };
    };
    $700: {
        paddingHorizontal: string;
        icon: {
            size: string;
        };
        label: {
            paddingHorizontal: string;
        };
    };
};
export declare const control: {
    $100: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $200: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $300: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $400: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $500: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $600: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $700: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $800: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
    $900: {
        minSize: string;
        borderRadius: string;
        gap: string;
    };
};
export declare const richIcon: {
    $100: {
        icon: {
            size: string;
        };
    };
    $200: {
        icon: {
            size: string;
        };
    };
    $300: {
        icon: {
            size: string;
        };
    };
    $400: {
        icon: {
            size: string;
        };
    };
    $500: {
        icon: {
            size: string;
        };
    };
    $600: {
        icon: {
            size: string;
        };
    };
    $700: {
        icon: {
            size: string;
        };
    };
    $800: {
        icon: {
            size: string;
        };
    };
    $900: {
        icon: {
            size: string;
        };
    };
};
export declare const semanticText: {
    headerXl: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerL: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerM: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerS: {
        paddingTop: string;
        paddingBottom: string;
    };
    headerXs: {
        paddingTop: string;
        paddingBottom: string;
    };
    paragraphL: {
        paddingTop: string;
        paddingBottom: string;
    };
    paragraphM: {
        paddingTop: string;
        paddingBottom: string;
    };
    paragraphS: {
        paddingTop: string;
        paddingBottom: string;
    };
};
export declare const components: {
    button: {
        $200: {
            paddingHorizontal: string;
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
            };
        };
        $300: {
            paddingHorizontal: string;
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
            };
        };
        $400: {
            paddingHorizontal: string;
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
            };
        };
        $500: {
            paddingHorizontal: string;
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
            };
        };
        $600: {
            paddingHorizontal: string;
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
            };
        };
        $700: {
            paddingHorizontal: string;
            icon: {
                size: string;
            };
            label: {
                paddingHorizontal: string;
            };
        };
    };
    control: {
        $100: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $200: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $300: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $400: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $500: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $600: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $700: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $800: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
        $900: {
            minSize: string;
            borderRadius: string;
            gap: string;
        };
    };
    richIcon: {
        $100: {
            icon: {
                size: string;
            };
        };
        $200: {
            icon: {
                size: string;
            };
        };
        $300: {
            icon: {
                size: string;
            };
        };
        $400: {
            icon: {
                size: string;
            };
        };
        $500: {
            icon: {
                size: string;
            };
        };
        $600: {
            icon: {
                size: string;
            };
        };
        $700: {
            icon: {
                size: string;
            };
        };
        $800: {
            icon: {
                size: string;
            };
        };
        $900: {
            icon: {
                size: string;
            };
        };
    };
    semanticText: {
        headerXl: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerL: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerM: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerS: {
            paddingTop: string;
            paddingBottom: string;
        };
        headerXs: {
            paddingTop: string;
            paddingBottom: string;
        };
        paragraphL: {
            paddingTop: string;
            paddingBottom: string;
        };
        paragraphM: {
            paddingTop: string;
            paddingBottom: string;
        };
        paragraphS: {
            paddingTop: string;
            paddingBottom: string;
        };
    };
};
//# sourceMappingURL=components.d.ts.map