/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const fonts: {
    display: {
        family: string;
        size: {
            '350': number;
            '400': number;
            '450': number;
            '500': number;
            '600': number;
            '650': number;
            '700': number;
        };
        lineHeight: {
            '350': number;
            '400': number;
            '450': number;
            '500': number;
            '600': number;
            '650': number;
            '700': number;
        };
        weight: {
            default: string;
            numeric: string;
            accent: string;
            'accent-numeric': string;
        };
    };
    text: {
        family: string;
        size: {
            '150': number;
            '200': number;
            '250': number;
            '300': number;
            '350': number;
            '400': number;
        };
        lineHeight: {
            '150': number;
            '200': number;
            '250': number;
            '300': number;
            '350': number;
            '400': number;
        };
        weight: {
            default: string;
            numeric: string;
            accent: string;
            'accent-numeric': string;
        };
    };
    compact: {
        family: string;
        size: {
            '150': number;
            '200': number;
            '250': number;
            '300': number;
            '350': number;
            '400': number;
        };
        lineHeight: {
            '150': number;
            '200': number;
            '250': number;
            '300': number;
            '350': number;
            '400': number;
        };
        weight: {
            default: string;
            numeric: string;
            accent: string;
            'accent-numeric': string;
        };
    };
};
//# sourceMappingURL=fonts.d.ts.map