/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const ios: {
    'layout.col-number.sm': number;
    'layout.col-number.md': number;
    'layout.col-number.lg': number;
    'layout.col-number.xl': number;
    'layout.gutter.sm': number;
    'layout.gutter.md': number;
    'layout.gutter.lg': number;
    'layout.gutter.xl': number;
};
export declare const android: {
    'layout.col-number.sm': number;
    'layout.col-number.md': number;
    'layout.col-number.lg': number;
    'layout.col-number.xl': number;
    'layout.gutter.sm': number;
    'layout.gutter.md': number;
    'layout.gutter.lg': number;
    'layout.gutter.xl': number;
};
export declare const web: {
    'layout.col-number.sm': number;
    'layout.col-number.md': number;
    'layout.col-number.lg': number;
    'layout.col-number.xl': number;
    'layout.gutter.sm': number;
    'layout.gutter.md': number;
    'layout.gutter.lg': number;
    'layout.gutter.xl': number;
};
export declare const platform: {
    ios: {
        'layout.col-number.sm': number;
        'layout.col-number.md': number;
        'layout.col-number.lg': number;
        'layout.col-number.xl': number;
        'layout.gutter.sm': number;
        'layout.gutter.md': number;
        'layout.gutter.lg': number;
        'layout.gutter.xl': number;
    };
    android: {
        'layout.col-number.sm': number;
        'layout.col-number.md': number;
        'layout.col-number.lg': number;
        'layout.col-number.xl': number;
        'layout.gutter.sm': number;
        'layout.gutter.md': number;
        'layout.gutter.lg': number;
        'layout.gutter.xl': number;
    };
    web: {
        'layout.col-number.sm': number;
        'layout.col-number.md': number;
        'layout.col-number.lg': number;
        'layout.col-number.xl': number;
        'layout.gutter.sm': number;
        'layout.gutter.md': number;
        'layout.gutter.lg': number;
        'layout.gutter.xl': number;
    };
};
//# sourceMappingURL=platform.d.ts.map