/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const settings: {
    defaultFont: string;
    fastSchemeChange: true;
    shouldAddPrefersColorThemes: true;
    allowedStyleValues: "somewhat-strict-web";
    themeClassNameOnRoot: true;
    onlyAllowShorthands: false;
};
//# sourceMappingURL=settings.d.ts.map