/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */
export declare const shapes: {
    'arrow-down': string;
    'arrow-up': string;
    'blocks-horizontal': string;
    'blocks-vertical': string;
    circle: string;
    'circles-tlbr': string;
    cross: string;
    diamond: string;
    hexagon: string;
    leaf: string;
    oval: string;
    rhombus: string;
    squircle: string;
};
//# sourceMappingURL=shapes.d.ts.map