/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const typography: {
    'font.brand': string;
    'font.text': string;
    'font-size.150': number;
    'font-size.200': number;
    'font-size.250': number;
    'font-size.300': number;
    'font-size.350': number;
    'font-size.400': number;
    'font-size.450': number;
    'font-size.500': number;
    'font-size.600': number;
    'font-size.650': number;
    'font-size.700': number;
    'font-size.800': number;
    'font-size.900': number;
    'line-height.default.150': number;
    'line-height.default.200': number;
    'line-height.default.250': number;
    'line-height.default.300': number;
    'line-height.default.350': number;
    'line-height.default.400': number;
    'line-height.default.450': number;
    'line-height.default.500': number;
    'line-height.default.600': number;
    'line-height.default.650': number;
    'line-height.default.700': number;
    'line-height.default.800': number;
    'line-height.default.900': number;
    'line-height.compact.150': number;
    'line-height.compact.200': number;
    'line-height.compact.250': number;
    'line-height.compact.300': number;
    'line-height.compact.350': number;
    'line-height.compact.400': number;
    'line-height.compact.450': number;
    'line-height.compact.500': number;
    'line-height.compact.600': number;
    'line-height.compact.650': number;
    'line-height.compact.700': number;
    'line-height.compact.800': number;
    'line-height.compact.900': number;
    'font-weight.brand.light': number;
    'font-weight.brand.default': number;
    'font-weight.brand.accent': number;
    'font-weight.text.light': number;
    'font-weight.text.default': number;
    'font-weight.text.accent': number;
    'paragraph-spacing.0': number;
    'paragraph-spacing.150': number;
    'paragraph-spacing.200': number;
    'paragraph-spacing.250': number;
    'paragraph-spacing.300': number;
    'paragraph-spacing.350': number;
    'paragraph-spacing.400': number;
    'paragraph-spacing.450': number;
    'paragraph-spacing.500': number;
    'paragraph-spacing.600': number;
    'paragraph-spacing.650': number;
    'paragraph-spacing.700': number;
    'paragraph-spacing.800': number;
    'paragraph-spacing.900': number;
};
//# sourceMappingURL=typography.d.ts.map