/**
 * @returns {string}
 */
function generateFileHeader() {
  return `
    /**
     * This file is automatically generated by @xsolla-zk/tokens
     * Do not edit it manually
    */
  `;
}

export default generateFileHeader;
