/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export const button = {
  $200: {
    paddingHorizontal: '$space.100',
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
    },
  },
  $300: {
    paddingHorizontal: '$space.200',
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
    },
  },
  $400: {
    paddingHorizontal: '$space.250',
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.150',
    },
  },
  $500: {
    paddingHorizontal: '$space.300',
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
    },
  },
  $600: {
    paddingHorizontal: '$space.350',
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
    },
  },
  $700: {
    paddingHorizontal: '$space.400',
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
    },
  },
};
export const control = {
  $100: {
    minSize: '$size.100',
    borderRadius: '$radius.200',
    gap: '$space.0',
  },
  $200: {
    minSize: '$size.200',
    borderRadius: '$radius.300',
    gap: '$space.100',
  },
  $300: {
    minSize: '$size.300',
    borderRadius: '$radius.300',
    gap: '$space.100',
  },
  $400: {
    minSize: '$size.400',
    borderRadius: '$radius.400',
    gap: '$space.100',
  },
  $500: {
    minSize: '$size.500',
    borderRadius: '$radius.500',
    gap: '$space.100',
  },
  $600: {
    minSize: '$size.600',
    borderRadius: '$radius.500',
    gap: '$space.150',
  },
  $700: {
    minSize: '$size.700',
    borderRadius: '$radius.550',
    gap: '$space.150',
  },
  $800: {
    minSize: '$size.800',
    borderRadius: '$radius.600',
    gap: '$space.200',
  },
  $900: {
    minSize: '$size.900',
    borderRadius: '$radius.700',
    gap: '$space.200',
  },
};
export const richIcon = {
  $100: {
    icon: {
      size: '$size.80',
    },
  },
  $200: {
    icon: {
      size: '$size.100',
    },
  },
  $300: {
    icon: {
      size: '$size.150',
    },
  },
  $400: {
    icon: {
      size: '$size.200',
    },
  },
  $500: {
    icon: {
      size: '$size.250',
    },
  },
  $600: {
    icon: {
      size: '$size.300',
    },
  },
  $700: {
    icon: {
      size: '$size.350',
    },
  },
  $800: {
    icon: {
      size: '$size.400',
    },
  },
  $900: {
    icon: {
      size: '$size.450',
    },
  },
};
export const semanticText = {
  headerXl: {
    paddingTop: '$space.400',
    paddingBottom: '$space.100',
  },
  headerL: {
    paddingTop: '$space.350',
    paddingBottom: '$space.100',
  },
  headerM: {
    paddingTop: '$space.300',
    paddingBottom: '$space.100',
  },
  headerS: {
    paddingTop: '$space.200',
    paddingBottom: '$space.100',
  },
  headerXs: {
    paddingTop: '$space.200',
    paddingBottom: '$space.100',
  },
  paragraphL: {
    paddingTop: '$space.100',
    paddingBottom: '$space.100',
  },
  paragraphM: {
    paddingTop: '$space.100',
    paddingBottom: '$space.100',
  },
  paragraphS: {
    paddingTop: '$space.100',
    paddingBottom: '$space.100',
  },
};
export const components = { button, control, richIcon, semanticText };
