/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export const button = {
  $200: {
    frame: {
      paddingHorizontal: '$space.100',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.200.accent',
      paddingHorizontal: '$space.100',
    },
  },
  $300: {
    frame: {
      paddingHorizontal: '$space.200',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.200.accent',
      paddingHorizontal: '$space.100',
    },
  },
  $400: {
    frame: {
      paddingHorizontal: '$space.250',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      typography: 'compact.250.accent',
      paddingHorizontal: '$space.150',
    },
  },
  $500: {
    frame: {
      paddingHorizontal: '$space.300',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      typography: 'compact.350.accent',
      paddingHorizontal: '$space.200',
    },
  },
  $600: {
    frame: {
      paddingHorizontal: '$space.350',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      typography: 'compact.350.accent',
      paddingHorizontal: '$space.200',
    },
  },
  $700: {
    frame: {
      paddingHorizontal: '$space.400',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      typography: 'compact.350.accent',
      paddingHorizontal: '$space.200',
    },
  },
};
export const control = {
  $100: {
    frame: {
      minSize: '$size.100',
      borderRadius: '$radius.200',
      gap: '$space.0',
    },
  },
  $200: {
    frame: {
      minSize: '$size.200',
      borderRadius: '$radius.300',
      gap: '$space.50',
    },
  },
  $300: {
    frame: {
      minSize: '$size.300',
      borderRadius: '$radius.300',
      gap: '$space.100',
    },
  },
  $400: {
    frame: {
      minSize: '$size.400',
      borderRadius: '$radius.400',
      gap: '$space.100',
    },
  },
  $500: {
    frame: {
      minSize: '$size.500',
      borderRadius: '$radius.500',
      gap: '$space.100',
    },
  },
  $600: {
    frame: {
      minSize: '$size.600',
      borderRadius: '$radius.500',
      gap: '$space.150',
    },
  },
  $700: {
    frame: {
      minSize: '$size.700',
      borderRadius: '$radius.550',
      gap: '$space.150',
    },
  },
  $800: {
    frame: {
      minSize: '$size.800',
      borderRadius: '$radius.600',
      gap: '$space.200',
    },
  },
  $900: {
    frame: {
      minSize: '$size.900',
      borderRadius: '$radius.700',
      gap: '$space.200',
    },
  },
};
export const richIcon = {
  $100: {
    icon: {
      size: '$size.80',
    },
  },
  $200: {
    icon: {
      size: '$size.100',
    },
  },
  $300: {
    icon: {
      size: '$size.150',
    },
  },
  $400: {
    icon: {
      size: '$size.200',
    },
  },
  $500: {
    icon: {
      size: '$size.250',
    },
  },
  $600: {
    icon: {
      size: '$size.300',
    },
  },
  $700: {
    icon: {
      size: '$size.350',
    },
  },
  $800: {
    icon: {
      size: '$size.400',
    },
  },
  $900: {
    icon: {
      size: '$size.450',
    },
  },
};
export const semanticText = {
  headerXl: {
    frame: {
      paddingTop: '$space.400',
      paddingBottom: '$space.100',
    },
  },
  headerL: {
    frame: {
      paddingTop: '$space.350',
      paddingBottom: '$space.100',
    },
  },
  headerM: {
    frame: {
      paddingTop: '$space.300',
      paddingBottom: '$space.100',
    },
  },
  headerS: {
    frame: {
      paddingTop: '$space.200',
      paddingBottom: '$space.100',
    },
  },
  headerXs: {
    frame: {
      paddingTop: '$space.200',
      paddingBottom: '$space.100',
    },
  },
  paragraphL: {
    frame: {
      paddingTop: '$space.100',
      paddingBottom: '$space.100',
    },
  },
  paragraphM: {
    frame: {
      paddingTop: '$space.100',
      paddingBottom: '$space.100',
    },
  },
  paragraphS: {
    frame: {
      paddingTop: '$space.100',
      paddingBottom: '$space.100',
    },
  },
};
export const components = { button, control, richIcon, semanticText };
