/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export const accordion = {
  $500: {
    header: {
      gap: '$space.200',
    },
  },
};
export const badge = {
  $500: {
    frame: {
      minSize: '$size.250',
      borderRadius: '$radius.300',
      gap: '$space.50',
      paddingHorizontal: '$space.150',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.300.numeric',
    },
  },
};
export const board = {
  list: {
    large: {
      frame: {
        paddingLeft: '$platform.layout.content-compensation.md',
        paddingRight: '$platform.layout.content-compensation.md',
        paddingVertical: '$space.350',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.200',
      },
    },
    medium: {
      frame: {
        paddingLeft: '$platform.layout.content-compensation.md',
        paddingRight: '$platform.layout.content-compensation.md',
        paddingVertical: '$space.350',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.200',
      },
    },
  },
  cell: {
    large: {
      frame: {
        paddingLeft: '$platform.layout.content-compensation.md',
        paddingRight: '$platform.layout.content-compensation.md',
        paddingVertical: '$space.200',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.700',
      },
    },
    medium: {
      frame: {
        paddingLeft: '$platform.layout.content-compensation.md',
        paddingRight: '$platform.layout.content-compensation.md',
        paddingVertical: '$space.200',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.600',
      },
    },
    small: {
      frame: {
        paddingLeft: '$platform.layout.content-compensation.md',
        paddingRight: '$platform.layout.content-compensation.md',
        paddingVertical: '$space.100',
        borderRadius: '$radius.550',
      },
      content: {
        minHeight: '$size.600',
      },
    },
  },
  accordion: {
    medium: {
      frame: {
        paddingLeft: '$platform.layout.content-compensation.md',
        paddingRight: '$space.200',
        paddingVertical: '$space.200',
        borderRadius: '$radius.500',
      },
      content: {
        minHeight: '$size.0',
      },
    },
  },
};
export const breadcrumbs = {
  $500: {
    frame: {
      gap: '$space.200',
    },
    item: {
      typography: 'compact.300.accent',
    },
  },
};
export const button = {
  $200: {
    frame: {
      paddingHorizontal: '$space.100',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.200.accent',
    },
  },
  $300: {
    frame: {
      paddingHorizontal: '$space.200',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      paddingHorizontal: '$space.100',
      typography: 'compact.200.accent',
    },
  },
  $400: {
    frame: {
      paddingHorizontal: '$space.250',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.150',
      typography: 'compact.250.accent',
    },
  },
  $500: {
    frame: {
      paddingHorizontal: '$space.300',
    },
    icon: {
      size: '$size.150',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.accent',
    },
  },
  $600: {
    frame: {
      paddingHorizontal: '$space.350',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.accent',
    },
  },
  $700: {
    frame: {
      paddingHorizontal: '$space.400',
    },
    icon: {
      size: '$size.200',
    },
    label: {
      paddingHorizontal: '$space.200',
      typography: 'compact.350.accent',
    },
  },
};
export const cell = {
  size: {
    large: {
      frame: {
        gap: '$space.300',
        paddingVertical: '$space.200',
      },
      content: {
        minHeight: '$size.250',
        paddingVertical: '$space.100',
      },
      slot: {
        minHeight: '$size.500',
      },
    },
    medium: {
      frame: {
        gap: '$space.250',
        paddingVertical: '$space.150',
      },
      content: {
        minHeight: '$size.200',
        paddingVertical: '$space.50',
      },
      slot: {
        minHeight: '$size.400',
      },
    },
  },
  addon: {
    gap: '$space.200',
  },
};
export const chips = {
  $200: {
    frame: {
      gap: '$space.100',
    },
    item: {
      typography: 'compact.200.default',
    },
  },
  $300: {
    frame: {
      gap: '$space.100',
    },
    item: {
      typography: 'compact.200.default',
    },
  },
  $400: {
    frame: {
      gap: '$space.100',
    },
    item: {
      typography: 'compact.250.default',
    },
  },
  $500: {
    frame: {
      gap: '$space.100',
    },
    item: {
      typography: 'compact.350.default',
    },
  },
  $600: {
    frame: {
      gap: '$space.100',
    },
    item: {
      typography: 'compact.350.default',
    },
  },
  $700: {
    frame: {
      gap: '$space.100',
    },
    item: {
      typography: 'compact.350.default',
    },
  },
};
export const control = {
  $100: {
    minSize: '$size.100',
    borderRadius: '$radius.200',
    gap: '$space.0',
  },
  $200: {
    minSize: '$size.200',
    borderRadius: '$radius.300',
    gap: '$space.50',
  },
  $300: {
    minSize: '$size.300',
    borderRadius: '$radius.300',
    gap: '$space.100',
  },
  $400: {
    minSize: '$size.400',
    borderRadius: '$radius.400',
    gap: '$space.100',
  },
  $500: {
    minSize: '$size.500',
    borderRadius: '$radius.500',
    gap: '$space.100',
  },
  $600: {
    minSize: '$size.600',
    borderRadius: '$radius.500',
    gap: '$space.150',
  },
  $700: {
    minSize: '$size.700',
    borderRadius: '$radius.550',
    gap: '$space.150',
  },
  $800: {
    minSize: '$size.800',
    borderRadius: '$radius.600',
    gap: '$space.200',
  },
  $900: {
    minSize: '$size.900',
    borderRadius: '$radius.700',
    gap: '$space.200',
  },
};
export const dropdown = {
  $400: {
    frame: {
      marginTop: '$space.100',
      padding: '$space.100',
      borderRadius: '$radius.400',
    },
    content: {
      paddingHorizontal: '$space.200',
    },
  },
  $500: {
    frame: {
      marginTop: '$space.200',
      padding: '$space.200',
      borderRadius: '$radius.500',
    },
    content: {
      paddingHorizontal: '$space.200',
    },
  },
  $600: {
    frame: {
      marginTop: '$space.200',
      padding: '$space.200',
      borderRadius: '$radius.500',
    },
    content: {
      paddingHorizontal: '$space.200',
    },
  },
};
export const field = {
  $400: {
    frame: {
      gap: '$space.100',
    },
    label: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
      typography: 'compact.250.default',
    },
    inputs: {
      gap: '$space.100',
    },
    hint: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
      typography: 'compact.250.default',
    },
  },
  $500: {
    frame: {
      gap: '$space.200',
    },
    label: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
      typography: 'compact.250.default',
    },
    inputs: {
      gap: '$space.100',
    },
    hint: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
      typography: 'compact.250.default',
    },
  },
  $600: {
    frame: {
      gap: '$space.200',
    },
    label: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
      typography: 'compact.250.default',
    },
    inputs: {
      gap: '$space.100',
    },
    hint: {
      gap: '$space.200',
      paddingHorizontal: '$space.350',
      typography: 'compact.250.default',
    },
  },
};
export const flexButton = {
  $300: {
    frame: {
      gap: '$space.0',
    },
    slot: {
      paddingLeft: '$space.50',
    },
  },
  $400: {
    frame: {
      gap: '$space.0',
    },
    slot: {
      paddingLeft: '$space.50',
    },
  },
  $500: {
    frame: {
      gap: '$space.0',
    },
    slot: {
      paddingLeft: '$space.50',
    },
  },
  $600: {
    frame: {
      gap: '$space.50',
    },
    slot: {
      paddingLeft: '$space.50',
    },
  },
  $700: {
    frame: {
      gap: '$space.50',
    },
    slot: {
      paddingLeft: '$space.100',
    },
  },
};
export const gallery = {
  $500: {
    gap: '$space.100',
  },
};
export const inlineInput = {
  $400: {
    typography: 'compact.250.default',
  },
  $500: {
    typography: 'compact.350.default',
  },
  $600: {
    typography: 'display.500.default',
  },
};
export const input = {
  $400: {
    frame: {
      borderWidth: '$stroke.200',
      paddingVertical: '$space.300',
      paddingHorizontal: '$space.350',
    },
    label: {
      typography: 'compact.250.default',
    },
  },
  $500: {
    frame: {
      borderWidth: '$stroke.200',
      paddingVertical: '$space.300',
      paddingHorizontal: '$space.350',
    },
    label: {
      typography: 'compact.350.default',
    },
  },
  $600: {
    frame: {
      borderWidth: '$stroke.200',
      paddingVertical: '$space.300',
      paddingHorizontal: '$space.350',
    },
    label: {
      typography: 'compact.350.default',
    },
  },
};
export const list = {
  $500: {
    frame: {
      gap: '$space.50',
    },
    title: {
      gap: '$space.200',
      typography: 'compact.300.accent',
    },
    subtitle: {
      gap: '$space.200',
      typography: 'compact.250.default',
    },
  },
  $600: {
    frame: {
      gap: '$space.50',
    },
    title: {
      gap: '$space.200',
      typography: 'compact.350.accent',
    },
    subtitle: {
      gap: '$space.200',
      typography: 'compact.250.default',
    },
  },
};
export const loader = {
  $500: {
    borderWidth: '$stroke.400',
  },
};
export const modal = {
  marginTop: '$space.350',
  marginBottom: '$space.200',
  borderRadius: '$radius.600',
  header: {
    paddingVertical: '$space.300',
    gap: '$space.300',
  },
  content: {
    paddingTop: '$space.100',
    paddingBottom: '$space.350',
  },
  footer: {
    paddingTop: '$space.100',
    paddingBottom: '$space.100',
  },
};
export const navBar = {
  size: {
    $500: {
      frame: {
        minHeight: '$size.450',
      },
      addonLeft: {
        paddingLeft: '$space.100',
        paddingRight: '$space.300',
        gap: '$space.200',
      },
      addonRight: {
        paddingLeft: '$space.300',
        paddingRight: '$space.100',
        gap: '$space.200',
      },
    },
  },
  content: {
    gap: '$space.50',
  },
};
export const pimple = {
  $200: {
    frame: {
      minSize: '$size.40',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.0',
    },
    icon: {
      size: '$size.40',
    },
    label: {
      typography: 'compact.150.accent-numeric',
    },
  },
  $300: {
    frame: {
      minSize: '$size.80',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.50',
    },
    icon: {
      size: '$size.40',
    },
    label: {
      typography: 'compact.150.accent-numeric',
    },
  },
  $400: {
    frame: {
      minSize: '$size.100',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.50',
    },
    icon: {
      size: '$size.60',
    },
    label: {
      typography: 'compact.150.accent-numeric',
    },
  },
  $500: {
    frame: {
      minSize: '$size.150',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.100',
    },
    icon: {
      size: '$size.80',
    },
    label: {
      typography: 'compact.200.accent-numeric',
    },
  },
  $600: {
    frame: {
      minSize: '$size.200',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.100',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.250.accent-numeric',
    },
  },
  $700: {
    frame: {
      minSize: '$size.300',
      borderRadius: '$radius.999',
      paddingHorizontal: '$space.200',
    },
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.300.accent-numeric',
    },
  },
};
export const progressBar = {
  $500: {
    frame: {
      height: '$size.20',
      borderRadius: '$radius.999',
    },
  },
};
export const richIcon = {
  $100: {
    icon: {
      size: '$size.80',
    },
    label: {
      typography: 'compact.150.numeric',
    },
  },
  $200: {
    icon: {
      size: '$size.100',
    },
    label: {
      typography: 'compact.200.numeric',
    },
  },
  $300: {
    icon: {
      size: '$size.150',
    },
    label: {
      typography: 'compact.250.numeric',
    },
  },
  $400: {
    icon: {
      size: '$size.200',
    },
    label: {
      typography: 'compact.300.numeric',
    },
  },
  $500: {
    icon: {
      size: '$size.250',
    },
    label: {
      typography: 'compact.350.numeric',
    },
  },
  $600: {
    icon: {
      size: '$size.300',
    },
    label: {
      typography: 'compact.350.numeric',
    },
  },
  $700: {
    icon: {
      size: '$size.350',
    },
    label: {
      typography: 'compact.400.numeric',
    },
  },
  $800: {
    icon: {
      size: '$size.400',
    },
    label: {
      typography: 'compact.400.numeric',
    },
  },
  $900: {
    icon: {
      size: '$size.450',
    },
    label: {
      typography: 'compact.400.numeric',
    },
  },
};
export const segmentedControl = {
  $300: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.400',
      borderWidth: '$stroke.100',
    },
  },
  $400: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.500',
      borderWidth: '$stroke.100',
    },
  },
  $500: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.550',
      borderWidth: '$stroke.100',
    },
  },
  $600: {
    frame: {
      paddingHorizontal: '$space.100',
      paddingVertical: '$space.100',
      borderRadius: '$radius.550',
      borderWidth: '$stroke.100',
    },
  },
};
export const selectionControl = {
  $400: {
    frame: {
      size: '$size.100',
      borderRadius: '$radius.200',
      borderWidth: '$stroke.100',
    },
    icon: {
      size: '$size.80',
    },
  },
  $500: {
    frame: {
      size: '$size.200',
      borderRadius: '$radius.300',
      borderWidth: '$stroke.100',
    },
    icon: {
      size: '$size.100',
    },
  },
  $600: {
    frame: {
      size: '$size.300',
      borderRadius: '$radius.300',
      borderWidth: '$stroke.200',
    },
    icon: {
      size: '$size.150',
    },
  },
};
export const semanticText = {
  headerXl: {
    paddingTop: '$space.0',
    paddingBottom: {
      base: '$space.150',
      $lg: '$space.200',
    },
    typography: {
      base: 'display.500.accent',
      $lg: 'display.600.accent',
      $xl: 'display.700.accent',
    },
  },
  headerL: {
    paddingTop: {
      base: '$space.50',
      $xl: '$space.100',
    },
    paddingBottom: '$space.200',
    typography: {
      base: 'display.450.accent',
      $lg: 'display.500.accent',
      $xl: 'display.600.accent',
    },
  },
  headerM: {
    paddingTop: '$space.100',
    paddingBottom: '$space.200',
    typography: {
      base: 'display.400.accent',
      $lg: 'display.450.accent',
      $xl: 'display.500.accent',
    },
  },
  headerS: {
    paddingTop: {
      base: '$space.150',
      $lg: '$space.50',
      $xl: '$space.100',
    },
    paddingBottom: {
      base: '$space.250',
      $lg: '$space.200',
    },
    typography: {
      base: 'display.350.accent',
      $lg: 'display.400.accent',
      $xl: 'display.450.accent',
    },
  },
  headerXs: {
    paddingTop: {
      base: '$space.150',
      $lg: '$space.50',
      $xl: '$space.100',
    },
    paddingBottom: '$space.250',
    typography: {
      base: 'compact.300.accent',
      $lg: 'display.350.accent',
      $xl: 'display.400.accent',
    },
  },
  paragraphL: {
    paddingTop: '$space.100',
    paddingBottom: '$space.200',
    typography: {
      base: 'text.350.default',
      $lg: 'text.400.default',
    },
  },
  paragraphM: {
    paddingTop: {
      base: '$space.0',
      $lg: '$space.100',
    },
    paddingBottom: {
      base: '$space.100',
      $lg: '$space.200',
    },
    typography: {
      base: 'text.300.default',
      $lg: 'text.350.default',
    },
  },
  paragraphS: {
    paddingTop: '$space.0',
    paddingBottom: '$space.100',
    typography: {
      base: 'text.250.default',
      $lg: 'text.300.default',
    },
  },
};
export const separator = {
  $500: {
    borderWidth: '$stroke.100',
  },
};
export const skeleton = {
  $500: {
    borderRadius: '$radius.300',
  },
};
export const slider = {
  $500: {
    frame: {
      height: '$size.20',
      borderRadius: '$radius.999',
    },
    knob: {
      size: '$size.150',
      borderWidth: '$stroke.100',
    },
  },
};
export const switchComponent = {
  $500: {
    frame: {
      borderRadius: '$radius.999',
      borderWidth: '$stroke.200',
      padding: '$space.100',
    },
    knob: {
      size: '$size.200',
      borderRadius: '$radius.999',
    },
  },
};
export const tabs = {
  $300: {
    frame: {
      gap: '$space.300',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $400: {
    frame: {
      gap: '$space.350',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $500: {
    frame: {
      gap: '$space.400',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $600: {
    frame: {
      gap: '$space.400',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
  $700: {
    frame: {
      gap: '$space.450',
    },
    line: {
      height: '$size.20',
      borderTopLeftRadius: '$radius.999',
      borderTopRightRadius: '$radius.999',
      borderBottomLeftRadius: '$radius.0',
      borderBottomRightRadius: '$radius.0',
    },
  },
};
export const tabBar = {
  $500: {
    tab: {
      minHeight: '$size.600',
      gap: '$space.100',
    },
    icon: {
      size: '$size.250',
    },
    label: {
      typography: 'compact.200.default',
    },
  },
};
export const components = {
  accordion,
  badge,
  board,
  breadcrumbs,
  button,
  cell,
  chips,
  control,
  dropdown,
  field,
  flexButton,
  gallery,
  inlineInput,
  input,
  list,
  loader,
  modal,
  navBar,
  pimple,
  progressBar,
  richIcon,
  segmentedControl,
  selectionControl,
  semanticText,
  separator,
  skeleton,
  slider,
  switchComponent,
  tabs,
  tabBar,
};
