/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export const web = {
  'layout.col-number.sm': 12,
  'layout.col-number.md': 12,
  'layout.col-number.lg': 12,
  'layout.col-number.xl': 12,
  'layout.gutter.sm': 24,
  'layout.gutter.md': 16,
  'layout.gutter.lg': 20,
  'layout.gutter.xl': 24,
};
export const ios = {
  'layout.col-number.sm': 1,
  'layout.col-number.md': 12,
  'layout.col-number.lg': 12,
  'layout.col-number.xl': 12,
  'layout.gutter.sm': 0,
  'layout.gutter.md': 0,
  'layout.gutter.lg': 0,
  'layout.gutter.xl': 0,
};
export const android = {
  'layout.col-number.sm': 12,
  'layout.col-number.md': 12,
  'layout.col-number.lg': 12,
  'layout.col-number.xl': 12,
  'layout.gutter.sm': 16,
  'layout.gutter.md': 16,
  'layout.gutter.lg': 20,
  'layout.gutter.xl': 24,
};
export const platform = { web, ios, android };
