/**
 * This file is automatically generated by @xsolla-zk-ui/tokens
 * Do not edit it manually
 */
export declare const media: {
    sm: {
        minWidth: number;
    };
    md: {
        minWidth: number;
    };
    lg: {
        minWidth: number;
    };
    xl: {
        minWidth: number;
    };
};
//# sourceMappingURL=android.d.ts.map