/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */
export declare const media: {
    md: {
        minWidth: number;
    };
    lg: {
        minWidth: number;
    };
    xl: {
        minWidth: number;
    };
};
//# sourceMappingURL=ios.d.ts.map