/**
 * This file is automatically generated by @xsolla-zk/tokens
 * Do not edit it manually
 */
export declare const media: {
    md: {
        minWidth: number;
    };
    maxMd: {
        maxWidth: number;
    };
    lg: {
        minWidth: number;
    };
    maxLg: {
        maxWidth: number;
    };
    xl: {
        minWidth: number;
    };
    maxXl: {
        maxWidth: number;
    };
};
//# sourceMappingURL=web.d.ts.map