export declare const ACCORDION_NAME = "Accordion";
export declare const ACCORDION_CONTEXT = "Accordion";
export declare const ACCORDION_TRIGGER_COMPONENT_NAME = "AccordionTrigger";
export declare const ACCORDION_ITEM_COMPONENT_NAME = "AccordionItem";
export declare const ACCORDION_HEADER_NAME = "AccordionHeader";
export declare const ACCORDION_KEYS: string[];
export declare const BADGE_COMPONENT_NAME = "Badge";
export declare const BUTTON_COMPONENT_NAME = "Button";
export declare const CELL_COMPONENT_NAME = "Cell";
export declare const CELL_BOARD_COMPONENT_NAME = "CellBoard";
export declare const CHECKBOX_COMPONENT_NAME = "Checkbox";
export declare const CHECKBOX_COMPONENT_INDICATOR_NAME = "CheckboxIndicator";
export declare const CHIPS_COMPONENT_NAME = "Chips";
export declare const CHIP_COMPONENT_NAME = "Chip";
export declare const DIALOG_COMPONENT_NAME = "Dialog";
export declare const DIALOG_HEADER_COMPONENT_NAME = "DialogHeader";
export declare const DIALOG_BODY_COMPONENT_NAME = "DialogBody";
export declare const DIALOG_FOOTER_COMPONENT_NAME = "DialogFooter";
export declare const DIALOG_TRIGGER_COMPONENT_NAME = "DialogTrigger";
export declare const DIALOG_PORTAL_COMPONENT_NAME = "DialogPortal";
export declare const DIALOG_OVERLAY_COMPONENT_NAME = "DialogOverlay";
export declare const DIALOG_CONTENT_COMPONENT_NAME = "DialogContent";
export declare const DIALOG_TITLE_COMPONENT_NAME = "DialogTitle";
export declare const DIALOG_DESCRIPTION_COMPONENT_NAME = "DialogDescription";
export declare const DIALOG_CLOSE_COMPONENT_NAME = "DialogClose";
export declare const DIALOG_WARNING_COMPONENT_NAME = "DialogWarning";
export declare const DIALOG_TITLE_WARNING_NAME = "DialogTitleWarning";
export declare const DIALOG_DESCRIPTION_WARNING_NAME = "DialogDescriptionWarning";
export declare const DIALOG_SHEET_CONTROLLER_COMPONENT_NAME = "DialogSheetController";
export declare const DIALOG_CONTEXT = "Dialog";
export declare const FIELD_COMPONENT_NAME = "Field";
export declare const FLEX_BUTTON_COMPONENT_NAME = "FlexButton";
export declare const INLINE_INPUT_COMPONENT_NAME = "InlineInput";
export declare const INPUT_COMPONENT_NAME = "Input";
export declare const INPUT_START_SLOT_COMPONENT_NAME = "InputStartSlot";
export declare const INPUT_END_SLOT_COMPONENT_NAME = "InputEndSlot";
export declare const LABEL_COMPONENT_NAME = "Label";
export declare const LIST_COMPONENT_NAME = "List";
export declare const LIST_BOARD_COMPONENT_NAME = "ListBoard";
export declare const LIST_TITLE_COMPONENT_NAME = "ListTitle";
export declare const LIST_TITLE_VALUE_COMPONENT_NAME = "ListTitleValue";
export declare const LIST_SUBTITLE_COMPONENT_NAME = "ListSubtitle";
export declare const LOADER_COMPONENT_NAME = "Loader";
export declare const MODAL_COMPONENT_NAME = "Modal";
export declare const MODAL_HEADER_COMPONENT_NAME = "ModalHeader";
export declare const MODAL_CONTENT_COMPONENT_NAME = "ModalContent";
export declare const MODAL_FOOTER_COMPONENT_NAME = "ModalFooter";
export declare const NAV_BAR_COMPONENT_NAME = "NavBar";
export declare const NAV_BAR_START_SLOT_COMPONENT_NAME = "NavBarStartSlot";
export declare const NAV_BAR_END_SLOT_COMPONENT_NAME = "NavBarEndSlot";
export declare const NAV_BAR_TITLE_COMPONENT_NAME = "NavBarTitle";
export declare const NAV_BAR_SUBTITLE_COMPONENT_NAME = "NavBarSubtitle";
export declare const NOTIFICATION_CONTEXT = "Notification";
export declare const NOTIFICATION_PROVIDER_NAME = "NotificationProvider";
export declare const NOTIFICATION_COMPONENT_NAME = "Notification";
export declare const NOTIFICATION_TITLE_COMPONENT_NAME = "NotificationTitle";
export declare const NOTIFICATION_DESCRIPTION_COMPONENT_NAME = "NotificationDescription";
export declare const NOTIFICATION_ACTION_COMPONENT_NAME = "NotificationAction";
export declare const NOTIFICATION_CLOSE_COMPONENT_NAME = "NotificationClose";
export declare const NOTIFICATION_ANNOUNCE_EXCLUDE_COMPONENT_NAME = "NotificationAnnounceExclude";
export declare const NOTIFICATION_IMPL_COMPONENT_NAME = "NotificationImpl";
export declare const NOTIFICATION_VIEWPORT_NAME = "NotificationViewport";
export declare const NOTIFICATION_VIEWPORT_WRAPPER_NAME = "NotificationViewportWrapper";
export declare const NOTIFICATION_VIEWPORT_DEFAULT_HOTKEY: string[];
export declare const NOTIFICATION_VIEWPORT_PAUSE = "notification.viewportPause";
export declare const NOTIFICATION_VIEWPORT_RESUME = "notification.viewportResume";
export declare const NOTIFICATION_FOCUS_PROXY_NAME = "NotificationFocusProxy";
export declare const OTP_FIELD_COMPONENT_NAME = "OTPField";
export declare const PIMPLE_COMPONENT_NAME = "Pimple";
export declare const PROGRESS_BAR_COMPONENT_NAME = "ProgressBar";
export declare const PROGRESS_BAR_ACTIVE_TRACK_NAME = "ProgressBarActiveTrack";
export declare const RADIO_GROUP_COMPONENT_NAME = "RadioGroup";
export declare const RADIO_GROUP_ITEM_NAME = "RadioGroupItem";
export declare const RADIO_GROUP_INDICATOR_NAME = "RadioGroupIndicator";
export declare const RICH_ICON_COMPONENT_NAME = "RichIcon";
export declare const RICH_ICON_SHAPES: {
    circle: string;
    squircle: string;
    rhombus: string;
    blocksHorizontal: string;
    circlesTLBR: string;
    leaf: string;
    arrowUp: string;
    arrowDown: string;
    diamond: string;
    oval: string;
    cross: string;
    hexagon: string;
    blocksVertical: string;
};
export declare const SEGMENTED_CONTROL_COMPONENT_NAME = "SegmentedControl";
export declare const SEGMENTED_CONTROL_SEGMENT_COMPONENT_NAME = "SegmentedControlSegment";
export declare const SEGMENTED_CONTROL_CONTEXT = "SegmentedControl";
export declare const SEMANTIC_TEXT_COMPONENT_NAME = "SemanticText";
export declare const SEPARATOR_COMPONENT_NAME = "Separator";
export declare const SHEET_COMPONENT_NAME = "Sheet";
export declare const SHEET_HEADER_COMPONENT_NAME = "SheetHeader";
export declare const SHEET_BODY_COMPONENT_NAME = "SheetBody";
export declare const SHEET_FOOTER_COMPONENT_NAME = "SheetFooter";
export declare const SHEET_HANDLE_COMPONENT_NAME = "SheetHandle";
export declare const SHEET_OVERLAY_COMPONENT_NAME = "SheetOverlay";
export declare const SHEET_SCROLL_VIEW_COMPONENT_NAME = "SheetScrollView";
export declare const SHEET_COVER_COMPONENT_NAME = "SheetCover";
export declare const SLIDER_COMPONENT_NAME = "Slider";
export declare const SLIDER_KNOB_NAME = "SliderKnob";
export declare const SLIDER_TRACK_NAME = "SliderTrack";
export declare const SLIDER_TRACK_ACTIVE_NAME = "SliderTrackActive";
export declare const PAGE_KEYS: string[];
export declare const ARROW_KEYS: string[];
export declare const BACK_KEYS: Record<'ltr' | 'rtl', string[]>;
export declare const SNACK_BAR_COMPONENT_NAME = "SnackBar";
export declare const SWITCH_COMPONENT_NAME = "Switch";
export declare const SWITCH_KNOB_COMPONENT_NAME = "SwitchKnob";
export declare const TAB_BAR_COMPONENT_NAME = "TabBar";
export declare const TAB_BAR_ITEM_COMPONENT_NAME = "TabBarItem";
export declare const TABS_COMPONENT_NAME = "Tabs";
export declare const TABS_TAB_COMPONENT_NAME = "TabsTab";
export declare const TABS_PANEL_COMPONENT_NAME = "TabsPanel";
export declare const TABS_LIST_COMPONENT_NAME = "TabsList";
export declare const TABS_LIST_INDICATOR_COMPONENT_NAME = "TabsListIndicator";
export declare const TABS_CONTEXT = "TabsContext";
export declare const TOAST_COMPONENT_NAME = "Toast";
export declare const DROPDOWN_COMPONENT_NAME = "Dropdown";
export declare const DROPDOWN_CONTENT_COMPONENT_NAME = "DropdownContent";
export declare const TOOLTIP_COMPONENT_NAME = "Tooltip";
//# sourceMappingURL=constants.d.ts.map