import type { MaskedInputProps } from './masked-input.types';
declare function MaskedInputBase({ mask, value, onChangeText, onKeyDown, ...props }: MaskedInputProps): import("react/jsx-runtime").JSX.Element;
export declare const MaskedInput: typeof MaskedInputBase & {
    StartSlot: ({ children, ...props }: Omit<import("@tamagui/core").GetProps<typeof import("@tamagui/core").Stack>, "children"> & {
        children: import("react").ReactNode | ((context: Omit<import("..").InputContextType, "size">) => import("react").ReactNode);
    }) => import("react").FunctionComponentElement<Omit<import("@tamagui/core").RNTamaguiViewNonStyleProps, keyof import("@tamagui/core").StackStyleBase> & import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase> & import("@tamagui/core").WithShorthands<import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase>> & import("@tamagui/core").WithPseudoProps<import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase> & import("@tamagui/core").WithShorthands<import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase>>> & import("@tamagui/core").WithMediaProps<import("@tamagui/core").WithThemeShorthandsAndPseudos<import("@tamagui/core").StackStyleBase, {}>> & import("react").RefAttributes<import("@tamagui/core").TamaguiElement>>;
    EndSlot: ({ children, ...props }: Omit<import("@tamagui/core").GetProps<typeof import("@tamagui/core").Stack>, "children"> & {
        children: import("react").ReactNode | ((context: Omit<import("..").InputContextType, "size">) => import("react").ReactNode);
    }) => import("react").FunctionComponentElement<Omit<import("@tamagui/core").RNTamaguiViewNonStyleProps, keyof import("@tamagui/core").StackStyleBase> & import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase> & import("@tamagui/core").WithShorthands<import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase>> & import("@tamagui/core").WithPseudoProps<import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase> & import("@tamagui/core").WithShorthands<import("@tamagui/core").WithThemeValues<import("@tamagui/core").StackStyleBase>>> & import("@tamagui/core").WithMediaProps<import("@tamagui/core").WithThemeShorthandsAndPseudos<import("@tamagui/core").StackStyleBase, {}>> & import("react").RefAttributes<import("@tamagui/core").TamaguiElement>>;
};
export {};
//# sourceMappingURL=masked-input.d.ts.map