name: Changelog & Release

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: 🚀 Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔖 Create Release with Changelog
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ github.ref_name }}
          title: "Release ${{ github.ref_name }}"