name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/xsolla-zk/xsolla-zk-ui/docs:${{ github.ref_name }}
            ghcr.io/xsolla-zk/xsolla-zk-ui/docs:cache
          cache-from: type=registry,ref=ghcr.io/xsolla-zk/xsolla-zk-ui/docs:cache
          cache-to: type=inline

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/xsolla-zk/xsolla-zk-ui/docs:${{ github.ref_name }}
            docker ps --filter "name=xsolla-zk-ui" -q | xargs -r docker stop || true
            docker rm xsolla-zk-ui-docs || true
            docker run -d --name xsolla-zk-ui-docs -p 3003:3000 ghcr.io/xsolla-zk/xsolla-zk-ui/docs:${{ github.ref_name }}
